version: '3'
services:
  nginx:
    image: nginx
    network_mode: bridge
    # container_name: editor-reverse-proxy
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000